

# ESP32-WROOM-DEV32D PINOUT - livingroom, diningroom, etc

D1: GPIO1 # U0_TXD CLK3 PWM - USE THIS PIN FOR SONIC TRIGGER PIN
D2: GPIO2 # LED ADC2_2 TOUCH2 CS PWM - STRAPPING PIN
D3: GPIO3 # U0_RXD CLK2 PWM -  USE THIS PIN FOR SONIC ECHO PIN
D4: GPIO4 # ADC2_0 TOUCH0 PWM
D5: GPIO5 # VSPI_CS PWM  - ALWAYS USE FOR SPI SETUP: CS PIN ON BME280  - STRAPPING PIN

D12: GPIO12 # ADC2_5 TOUCH5 HSPI_MISO PWM  - STRAPPING PIN
D13: GPIO13 # ADC2_4 TOUCH4 HSPI_MOSI PWM
D14: GPIO14 # ADC2_6 TOUCH6 HSPI_CLK PWM - ALWAYS USE FOR SPI SETUP: SCK PIN ON BME280
D15: GPIO15 # ADC2_3 TOUCH3 HSPI_CS PWM   - STRAPPING PIN
D16: GPIO16 # U2_RXD PWM - ALWAYS USE THIS PIN FOR SONIC ECHO PIN
D17: GPIO17 # U2_TXD PWM - ALWAYS USE THIS PIN FOR SONIC TRIGGER PIN
D18: GPIO18 # SCK VSPI_CLK PWM 
D19: GPIO19 # MISO VSPI_MISO PWM - ALWAYS USE FOR SPI SETUP: SDO PIN ON BME280
D21: GPIO21 # SDA PWM - ALWAYS FOR SDA I2C TEMP/HUMIDITY SENSOR - ALWAYS USE FOR I2C SETUP: SDI PIN ON BME280
D22: GPIO22 # SCL PWM - ALWAYS FOR SCL I2C TEMP/HUMIDITY SENSOR - ALWAYS USE FOR I2C SETUP: SCK PIN ON BME280
D23: GPIO23 # MOSI VSPI_MOSI PWM  - ALWAYS USE FOR SPI SETUP: SDI PIN ON BME280
D25: GPIO25 # ADC2_8 DAC1 PWM
D26: GPIO26 # ADC2_9 DAC2 PWM
D27: GPIO27 # ADC2_7 TOUCH7 PWM
D32: GPIO32 # ADC1_4 TOUCH9 PWM 
D33: GPIO33 # ADC1_5 TOUCH8 PWM NO OUTPUT LIKE BUZZERS
D34: GPIO34 # ADC1_6 PWM NO OUTPUT LIKE BUZZERS  - NO PULLUP
D35: GPIO35 # ADC1_7 PWM NO OUTPUT LIKE BUZZERS - NO PULLUP

VP: GPIO36 # ADC1_0 PWM NO OUTPUT LIKE BUZZERS - NO PULLUP
VN: GPIO39 # ADC1_3 PWM NO OUTPUT LIKE BUZZERS - NO PULLUP



RX0: GPIO3 #   RPIN34  G3   P3  D3  PIN34  
TX0: GPIO1 #   RPIN35  G1   P1  D1  PIN35
RX1: GPIO9 #   LPIN16  G9   P9  D9  PIN16
TX1: GPIO10 #  LPIN17  G10  P10 D10 PIN17
RX2: GPIO16 #  RPIN27  G16  P16 D16 PIN27
TX2: GPIO17 #  RPIN28  G17  P17 D17 PIN28
SDA: GPIO21 #  RPIN33  G21  P21 D21 PIN33
SCL: GPIO22 #  RPIN36  G22  P22 D22 PIN36


##################################################################################################################################################################


# LIST IS BY ACTUAL PINS ON ARDUINO


# LEFT SIDE - DESCENDING
PIN1: '3.3v' # DOES NOT SHOW ON BREAKOUT BOARD
PIN2: 'RESET' # -- EN 
PIN3: GPIO36 # ADC0           -- SVP
PIN4: GPIO39 # ADC3            -- SVN 
PIN5: GPIO34 # ADC6          -- P34
PIN6: GPIO35 # ADC7          -- P35
PIN7: GPIO32 # ADC4 TOUCH9     -- P32
PIN8: GPIO33 # ADC5 TOUCH 8     -- P33
PIN9: GPIO25 # ADC18 DAC1      -- P25 
PIN10: GPIO26 # ADC19 DAC2    -- P26
PIN11: GPIO27 # ADC17 TOUCH7 -- P27
PIN12: GPIO14 # ADC16 TOUCH6 -- P14
PIN13: GPIO12 # ADC15 TOUCH5 -- P12 # DO NOT USE
PIN14: GPIO13 # ADC14 TOUCH4 -- P13

# RIGHT SIDE - DESCENDING
PIN37: GPIO23 # VSPI MOSI -- P23
PIN36: GPIO22 # I2C SCL   -- P22 
PIN35: GPIO1 # TX0        -- TX
PIN34: GPIO3 # RX0        -- RX 
PIN33: GPIO21 # I2C SDA  -- P21
PIN31: GPIO19 # VSPI MISO -- P19
PIN30: GPIO18 # VSPI SCK  -- P18
PIN29: GPIO5 # VSPI SS    -- P5
PIN28: GPIO17 # TX2       -- P17
PIN27: GPIO16 # RX2       -- P16
PIN26: GPIO4 # ADC TOUCH0 -- P4
PIN24: GPIO2 # ADC TOUCH2 -- P2 # DO NOT USE
PIN23: GPIO15 # ADC13 TOUCH3 -- P15 # DO NOT USE


